# Generated by Django 3.0.6 on 2020-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200620_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
