# Generated by Django 3.0.6 on 2020-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='location',
            new_name='repository',
        ),
    ]
